### ISSUE TITLE
Observing many logs in the format "Connecting to %s"

### ISSUE THREAD

**Issue by tomfotherby** [kubernetes-csi/livenessprobe#110]
We are using livenessprobe `v2.2.0` and see many logs in `stderr` that look like this:

    1 connection.go:153] Connecting to unix:///csi/csi.sock

I tracked the line of code that generates these log messages to the golang `connection` library:

    klog.V(5).Infof("Connecting to %s", address)

Source: https://github.com/kubernetes-csi/csi-lib-utils/blob/v0.9.1/connection/connection.go#L153 . Although the `V(5)` was added only 3 months ago, 29/Dec/20 in https://github.com/kubernetes-csi/csi-lib-utils/commit/75fbafda323a769af69e76bbe37dcf73276fce46.

We configure the livenessprobe sidecar like this:

```
      - args:
        - --csi-address=/csi/csi.sock
        - --health-port=9808
        - --v=3
        image: k8s.gcr.io/sig-storage/livenessprobe:v2.2.0
        imagePullPolicy: IfNotPresent
        name: liveness-probe
        resources:
          limits:
            cpu: 50m
            memory: 32Mi
          requests:
            cpu: 10m
            memory: 8Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /csi
          name: socket-dir
```

My understanding was that the `V(5)` in the Connection logging whould mean that if we used `--v=5` we would see the log, but since we use `--v=3`, we shouldn't see it.

Are we doing something wrong? or do we simply need to wait until v2.3 to pickup the new `V(5)` added to the connection library logging?

---

I noticed in the [v2.2 CHANGELOG](https://github.com/kubernetes-csi/livenessprobe/blob/master/CHANGELOG/CHANGELOG-2.2.md), there was a PR to reduce the default log level of the livenessprobe-sidecar to '4' (https://github.com/kubernetes-csi/livenessprobe/pull/88). 

---

Currently we get about 20,000 logs like this per hour, which is wasting space in ElasticSearch. As a workaround we can filter out these logs with a logstash filter, for example:

```
    filter {
      if [kubernetes][container][name] == "liveness-probe" {
        if "Connecting to unix:///csi/csi.sock" in [message] {
          drop{}
        }
      }
    }
```
