### ISSUE TITLE
livenessprobe consumes too much memory 

### ISSUE THREAD

**Issue by leakingtapan** [kubernetes-csi/livenessprobe#45]
I ran the CSI driver with liveness probe for several days and the liveness probe memory usage turned to be 765MB which is abnormal compared to other csi sidecars. 

The follow is a screenshot from `htop`:

<img width="1280" alt="Screen Shot 2019-04-14 at 5 39 16 PM" src="https://user-images.githubusercontent.com/5259480/56101921-842f8180-5edd-11e9-96ac-527f202b136e.png">

Another side affect is my CSI driver turned to be crashing a lot more after liveness probe is enabled:

```
NAMESPACE     NAME                                                    READY   STATUS    RESTARTS   AGE
kube-system   dns-controller-64db5996cd-wvrmv                         1/1     Running   0          6d7h
kube-system   ebs-csi-controller-0                                    6/6     Running   36         5d18h
kube-system   ebs-csi-node-djvrx                                      3/3     Running   20         5d18h
kube-system   ebs-csi-node-g2c2k                                      3/3     Running   9          5d18h
```

Here is my liveness probe config:
```
          livenessProbe:
            httpGet:
              path: /healthz
              port: healthz
            initialDelaySeconds: 10
            timeoutSeconds: 3
            periodSeconds: 10
            failureThreshold: 5
```
